name: Build http-stress-test

on:
  push:
    branches:
      - main
    paths:
      - 'http-stress-test/**'

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-publish:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: http-stress-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Set docker repository
      run: echo "REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/http-stress-test" >> $GITHUB_ENV
    - name: Build Docker image
      run: docker build -t ghcr.io/$REPOSITORY:latest .
    - name: Tag Docker image
      run: docker tag ghcr.io/$REPOSITORY:latest ghcr.io/$REPOSITORY:commit-${GITHUB_SHA:0:8}
    - name: Push Docker image
      run: docker push ghcr.io/$REPOSITORY --all-tags
